DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Process;
DROP TABLE IF EXISTS Task;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS Skills;
DROP TABLE IF EXISTS Employee_roles;
DROP TABLE IF EXISTS Employee_skills;
DROP TABLE IF EXISTS Affiliation;
DROP TABLE IF EXISTS Company_Profile;
DROP TABLE IF EXISTS Employee_Profile;
DROP TABLE IF EXISTS Employee_affiliation;
CREATE TABLE Employee (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
);
CREATE TABLE Process (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    details TEXT,
);
CREATE TABLE Task (
    id INT AUTO_INCREMENT PRIMARY KEY,
    process_id INT,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (process_id) REFERENCES Process(id)
);
CREATE TABLE Roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL,
);
CREATE TABLE Skills (
    id INT AUTO_INCREMENT PRIMARY KEY,
    skill_name VARCHAR(100) NOT NULL,
);
CREATE TABLE Employee_roles (
    role_id INT NOT NULL,
    employee_id INT NOT NULL,
    PRIMARY KEY (role_id, employee_id),
    FOREIGN KEY (role_id) REFERENCES Roles(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES Employee(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE Employee_skills (
    skill_id INT NOT NULL,
    employee_id INT NOT NULL,
    PRIMARY KEY (skill_id, employee_id),
    FOREIGN KEY (skill_id) REFERENCES Skills(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES Employee(id) ON DELETE CASCADE ON UPDATE CASCADE
);