DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Process;
DROP TABLE IF EXISTS Task;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS Skills;
DROP TABLE IF EXISTS Employee_roles;
DROP TABLE IF EXISTS Employee_skills;
CREATE TABLE Employee ();